name: Deploy Community Service

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to OCIR
        run: |
          echo "${{ secrets.OCIR_AUTH_TOKEN }}" | docker login \
            -u "${{ secrets.OCIR_USERNAME }}" \
            --password-stdin ap-chuncheon-1.ocir.io

      - name: Build Docker image
        run: docker build -t community-service .

      - name: Tag image for OCIR
        run: |
          docker tag community-service \
            ap-chuncheon-1.ocir.io/axuvlb6gzvbg/diary/app:community-latest

      - name: Push image to OCIR
        run: docker push ap-chuncheon-1.ocir.io/axuvlb6gzvbg/diary/app:community-latest
